# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js 12'

  - script: |
      npm install --progress=false --loglevel=error --no-fund
      npm run coverage
    displayName: 'npm install and test'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: 'Coverage/test-results.xml'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'

  - script: |
      npm pack
    displayName: 'Create package'

  - task: CopyFiles@2
    inputs:
      contents: '*.tgz'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy package to artifacts staging directory'

  - task: PublishBuildArtifacts@1
    inputs:
      path: $(Build.ArtifactStagingDirectory)
      artifact: package
    displayName: 'Publish artifacts'
